name: Expense-Tracking CI/CD Workflow

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
 build:
  strategy:
    matrix:
      os: [ubuntu-latest, windows-latest, macos-latest]
      version: [12, 14, 16]
      include:
        - os: windows-latest
          version: 16
          npm: 6
  runs-on: ${{ matrix.os }}
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Using NodeJS ${{ matrix.version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.version }}
        cache: 'npm'
    - if: ${{ matrix.npm }}
      run: npm install -g npm@${{ matrix.npm }}
    - name: Install dependencies
      run: npm ci
    - name: Build project
      run: npm run build
    
    
