name: Expense-Tracking CI/CD Workflow

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
 build:
  strategy:
    matrix:
      platform: [ubuntu-latest, macos-latest, windows-latest]
      version: [14, 16, 18]
      exclude:
        - platform: ubuntu-latest
          version: 18 
  runs-on: ${{ matrix.platform }}
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Using NodeJS ${{ matrix.version }}
      uses: actions/setup-node@v3
      with:
        node-version: "${{ matrix.version }}"
    - name: Install dependencies
      run: npm ci
    - name: Build project
      run: npm run build
    
    
